
GET http://localhost:8000/items HTTP/1.1

###

GET http://localhost:8000/items/BK-1007 HTTP/1.1

###

###

POST http://localhost:8000/add HTTP/1.1
content-type: application/json

{
    "title": "test",
    "author": "person",
    "genre": "buddhism",
    "price": "5.99",
    "stock_quantity": "20",
    "isbn": "978-05se425559474"
}

###

DELETE  http://localhost:8000/items/uepmMOb5gZk HTTP/1.1

###

PATCH http://localhost:8000/items/BK-1007 HTTP/1.1
content-type: application/json

{ 
    "title": "Sapiens",
    "author": "Yuval Noah Harari",
    "genre": "History",
    "price": 22.99,
    "isbn": "978-0062316097",
    "stock_quantity": "20"
}